### ISSUE TITLE
Submit to upstream?

### ISSUE THREAD

**Issue by kaushalmodi** [atdt/advcpmv#3]
It would be awesome if you can submit this patch upstream. Is it that you cannot or do not want to assign the copyright to FSF? Or was this feature rejected by the coreutils dev team?

Copying @eggert.. can something like this be integrated into the coreutils cp? If not, then probably as a new binary?

**Comment by timofonic** [comment]
@kaushalmodi @eggert It would be very nice! dd already has a progress bar. What about the rest?

@atdt @boscowitch @schollz Any news?

**Comment by atdt** [comment]
I am not the author of the code. It was released under GPL v3 so (AFAIK, IANAL, etc.) it can be submitted upstream by anyone.

**Comment by mrdrogdrog** [comment]
As you can see in commit https://github.com/mrdrogdrog/advcpmv/commit/6c24520ccfecf69497ce865a1a3abd8f83d8c433 of my fork, the gnu devs won't merge this feature.

**Comment by kaushalmodi** [comment]
@mrdrogdrog Oh well. Thanks for the update.
